#!/bin/bash

set -e

#usage
usage() {
USAGE="
=========================================================
                  MGEcatcher (v$VERSION)

Automated pipeline to identify mobile genetic elements in
                  long read DNA data
=========================================================
by Vinícius H Franceschini Santos, 2020

\e[4mUsage\e[0m:

MGEcatcher --reads <reads.fq> --mge_seq <mge.fa> [--threads <N>] \\
           --output <path/to/output/> --barcode <BC01>

\e[4mRequired arguments\e[0m:

   --reads        Fastq file for basecalled reads to be used as subject
   --mge_seq      Fasta file containing MGE sequences to be used as query
   --output       Output dir name; will be created if does not exist
   --barcode      Barcode identifier (ex.: BC01)

\e[4mOptional arguments\e[0m:

   --threads      Number of threads (default: 10)

"
printf "%s\\n" "$USAGE"
exit 2
}

# error function
error_exit() {
        msg=$1
        exit_code=${2:-1}
        echo -e "\033[1;31m${msg}\033[0m"
        usage
}

check_deps() {
    for app in $CONDA_PREFIX/bin/blastn $CONDA_PREFIX/bin/bedtools; do
        command -v $app >/dev/null 2>&1 || error_exit \
                "ERROR: Cannot find ${app}. Make sure it is installed and in your PATH variable"
    done
}

VERSION=0.2
check_deps


HOME_DIR=${0%/*}
# Log message function (normal text)
log() {
	echo [$(date +%Y-%m-%d" "%H:%M:%S)] $1
}
# Warning message function (yellow text)
warn() {
	echo -e "\033[1;33m"[$(date +%Y-%m-%d" "%H:%M:%S)] $1"\033[0m"
	}
# "Done" message function
DONEmsg() {
	echo -e [$(date +%Y-%m-%d" "%H:%M:%S)] Done!
}
# parse args

THREADS=10
# option strings
SHORT=h
LONG=help,reads:,barcode:,mge_seq:,output:,threads:

# read the options
OPTS=$(getopt --options $SHORT --long $LONG --name "$0" -- "$@")
if [ $? != 0 ] ; then echo "Failed to parse options...exiting." ; exit 1 ; fi
eval set -- "$OPTS"
while true ; do
  case "$1" in
    -h | --help )
      usage
      ;;
    r)
      READS=${OPTARG}
      ;;
    t)
      THREADS=${OPTARG}
      ;;
    m)
       MGE=${OPTARG}
      ;;
    o)
       OUTPUT=${OPTARG}
      ;;
    b)
      BC=${OPTARG}
     ;;
  esac
done

declare -A array # associative arrays need to be declared!
array=( [-r]="${READS}" [-m]="${MGE}" [-o]="${OUTPUT}" [-b]="${BC}" )

for idx in "${!array[@]}"; do
	if [[ ! ${array[$idx]} ]]; then
	echo "ERROR: $idx argument must be supplied. exiting..."
	usage
	fi
done


echo "=========================================================
                  MGEcatcher (v$VERSION)

Automated pipeline to identify mobile genetic elements in
                  long read DNA data
---------------------------------------------------------
Reads: ${READS}
MGE file: ${MGE}
Output: ${OUTPUT}
Threads: ${THREADS}
Identifier: ${BC}
========================================================="

# make temp files
mkdir -p ${OUTPUT}
mkdir -p ${OUTPUT}/tmp/

READ_BNAME=`basename ${READS}`

FASTA=${OUTPUT}/tmp/${READ_BNAME%.*}.fasta

if [ ! -f ${FASTA} ]; then
	log "Converting fastq to fasta..."
	sed -n '1~4s/^@/>/p;2~4p' ${READS} > ${FASTA}
	DONEmsg
else
	warn "file ${FASTA} already exists... skipping"
fi

if [ ! -f ${FASTA}.nsq ]; then
	log "Creating database for BLAST..."
	$CONDA_PREFIX/bin/makeblastdb -in ${FASTA} \
		-dbtype nucl > /dev/null 2> /dev/null
	DONEmsg
else
	warn "Blast database already exists... skipping"
fi

MAPPINGOUT=${OUTPUT}/tmp/${READ_BNAME%.*}.MGE-mapping

if [ ! -f "${MAPPINGOUT}" ]; then
        log "Mapping MGEs with ${MGE}"
        $CONDA_PREFIX/bin/blastn -db ${FASTA} -query ${MGE} \
		-strand plus \
		-evalue 1e-03 \
		-outfmt "7 qacc sacc sstart send qlen slen evalue" \
		-task blastn -num_threads ${THREADS} \
		-out $MAPPINGOUT > ${OUTPUT}/tmp/MGE-mapping.err 2>&1
		DONEmsg
else
	warn "MGE-mapping already done... skipping"
fi

REDUCED=${MAPPINGOUT}.filtered.reduced.txt
if [ ! -f ${REDUCED} ]; then
        log "Filtering results"
        # First step, select only those which size is approx. equal to MGE
        # length (i.e., more or less 10% of MGE size)
        cat $MAPPINGOUT | \
        	awk '{ if ($4 - $3 >= $5 * 0.9 && $4 - $3 <= $5 * 1.1){print $0}}' \
        	> ${MAPPINGOUT}.filtered
        # Second, apply the reduce function to remove overlapping
        # alignments
        $CONDA_PREFIX/bin/Rscript "$HOME_DIR"/ReduceOverlappingMGEs.R \
                ${MAPPINGOUT}.filtered \
        > /dev/null
        cp ${MAPPINGOUT}.filtered ${OUTPUT}/${BC}.reduced.txt
        log "Done"
else
        warn "filtered results exist... skipping"
fi

if [ ! -f ${REDUCED}.upstream ]; then
        log "Retrieving MGE name information (this takes some time)"

        while read line; do
                grep -f <(echo $line | awk -v OFS="\t" '{ print $1, $2, $3 }') \
                ${MAPPINGOUT} | head -n1
        done < ${REDUCED} > ${REDUCED}.mge

	log "Parsing BLAST results"

	log "Writting files to be analyzed separetelly"
	#a. hits for which we cannot extract 150bp upstreeam the MGE"
	grep -v "#" ${REDUCED}.mge | \
		awk 'BEGIN{OFS="\t"}{if($3<150){print$0}}' \
		> ${REDUCED}.upstream

        #b. hits for which we cannot extract 150bp downstream the MGE (read ends before it)"
	grep -v "#" ${REDUCED}.mge | \
		awk 'BEGIN{OFS="\t"}{if($4>$6-150){print$0}}' \
		> ${REDUCED}.downstream

	#writing hits that cannot be use (both 1 and 2 are true)"
	grep -v "#" ${REDUCED}.mge | \
		awk 'BEGIN{OFS="\t"}{if($4>$6-150 && $3<150){print$0}}' \
		> ${REDUCED}.anything

	DONEmsg
	# we have hits that can easily extract the 300bp window

	grep -v "#" ${REDUCED}.mge | \
		grep -v -f ${REDUCED}.upstream | \
		grep -v -f ${REDUCED}.downstream \
		> ${REDUCED}.extract


	# here I am writting the query files. I editted the query name so
	# that it contains: (i) the name of the read the MGE was mapped
	# (ii) the MGE size, and (iii) the MGE name. These three fields are
	# separated by '_' (see the last awk field: $2_$5_$1)

	log "Writting upstream flank sequences"
	$CONDA_PREFIX/bin/bedtools getfasta -fi ${FASTA} -name -bed <(cat \
		${REDUCED}.extract | \
		awk 'BEGIN{OFS="\t"}{ print $2, $3-150, $3, $2"_"$5"_"$1}') \
		> ${REDUCED}.query.upstream 2> /dev/null

	#writting downstream flank sequences"
	$CONDA_PREFIX/bin/bedtools getfasta -fi ${FASTA} -name -bed <(cat \
		${REDUCED}.extract | \
		awk 'BEGIN{OFS="\t"}{ print $2, $4, $4+150, $2"_"$5"_"$1}') \
		> ${REDUCED}.query.downstream

	log "Merging upstream and downstream flanks"
	$CONDA_PREFIX/bin/python "$HOME_DIR"/MergeUpstreamDownstream.py \
		-u ${REDUCED}.query.upstream \
		-d ${REDUCED}.query.downstream \
		-o ${REDUCED}.query.merged
	DONEmsg
else
	warn "Results already parsed... skipping"
fi

cp ${REDUCED}.query.merged ${OUTPUT}/${BC}-flanks-query.fa
BLASTOUT=${REDUCED}.blastn

if [ ! -f "${BLASTOUT}" ]; then
        log "Querying 300bp frags with BLASTn"
        $CONDA_PREFIX/bin/blastn -db ${FASTA} -query ${REDUCED}.query.merged \
		-evalue 1e-03 \
		-outfmt "7 qacc sacc sstart send length qlen slen evalue" \
		-task megablast -num_threads ${THREADS} -strand plus \
		-out $BLASTOUT > ${OUTPUT}/tmp/blastn.err 2>&1
		DONEmsg
else
	warn "MGE-mapping already done... skipping"
fi

cp "${BLASTOUT}" "${OUTPUT}/${BC}-flanks-results.outfmt7"
CLASSIFICATION="${OUTPUT}/${BC}_CLASSIFICATION/"

mkdir -p "${CLASSIFICATION}"

if [ ! -f "${CLASSIFICATION}/${BC}.optionalMGEs.txt" ]; then
	log "Classificating reads as fixed or optional"
	$CONDA_PREFIX/bin/python "$HOME_DIR"/scripts/GetNonFixedReads.py \
		--input "${BLASTOUT}" \
		--prefix "${BC}" \
		--output "${CLASSIFICATION}"
	DONEmsg
	log "Removing temporary files"
	rm -rf "${OUTPUT}"/tmp
	DONEmsg
else
	warn "Classification already done... skipping"
fi

#bash bbmap/filterbyname.sh \
#        in="${READS}" \
#        names="${CLASSIFICATION}/${BC}.optionalMGEs-readnames.txt" \
#        out="${OUTPUT}/${BC}-to-assembly.fastq" \
#        include=f qin=33
